#define VECTOR_NEXT		1
#define VECTOR_PREV		2
#define VECTOR_WAYPOINT	3
#define VECTOR_QUEST	4
#define TARGET_LEVEL	-1

typedef struct LevelVectorArray_t
{
	DWORD dwCurrentLevel;
	DWORD dwVectorType;
	DWORD dwTarget;
	DWORD dwTargetType;
} LVA, *LPLVA;

LVA MapVectors[] = {

				/////////////////////////////////////////////
				/////////////////   Act I   /////////////////
				/////////////////////////////////////////////

	{MAP_A1_BLOOD_MOOR, VECTOR_NEXT, MAP_A1_COLD_PLAINS, TARGET_LEVEL},
	//{MAP_A1_BLOOD_MOOR, VECTOR_PREV, MAP_A1_ROGUE_ENCAMPMENT, TARGET_LEVEL},
	{MAP_A1_BLOOD_MOOR, VECTOR_QUEST, MAP_A1_DEN_OF_EVIL, TARGET_LEVEL},

	{MAP_A1_DEN_OF_EVIL, VECTOR_QUEST, 774, UNIT_TYPE_NPC},
	{MAP_A1_DEN_OF_EVIL, VECTOR_PREV, MAP_A1_BLOOD_MOOR, TARGET_LEVEL},

	{MAP_A1_COLD_PLAINS, VECTOR_NEXT, MAP_A1_STONY_FIELD, TARGET_LEVEL},
	{MAP_A1_COLD_PLAINS, VECTOR_PREV, MAP_A1_BLOOD_MOOR, TARGET_LEVEL},
	{MAP_A1_COLD_PLAINS, VECTOR_QUEST, MAP_A1_BURIAL_GROUNDS, TARGET_LEVEL},

	{MAP_A1_BURIAL_GROUNDS, VECTOR_QUEST, 805, UNIT_TYPE_NPC},
	{MAP_A1_BURIAL_GROUNDS, VECTOR_PREV, MAP_A1_COLD_PLAINS, TARGET_LEVEL},

	{MAP_A1_STONY_FIELD, VECTOR_NEXT, MAP_A1_UNDERGROUND_PASSAGE_LEVEL_1, TARGET_LEVEL},
	{MAP_A1_STONY_FIELD, VECTOR_PREV, MAP_A1_COLD_PLAINS, TARGET_LEVEL},
	{MAP_A1_STONY_FIELD, VECTOR_QUEST, 17, UNIT_TYPE_OBJECT},

	{MAP_A1_TRISTRAM, VECTOR_NEXT, 268, UNIT_TYPE_OBJECT},
	{MAP_A1_TRISTRAM, VECTOR_QUEST, 26, UNIT_TYPE_OBJECT},

	{MAP_A1_THE_SECRET_COW_LEVEL, VECTOR_QUEST, 773, UNIT_TYPE_NPC},
	{MAP_A1_THE_SECRET_COW_LEVEL, VECTOR_PREV, 60, UNIT_TYPE_OBJECT},

	{MAP_A1_UNDERGROUND_PASSAGE_LEVEL_1, VECTOR_NEXT, MAP_A1_DARK_WOOD, TARGET_LEVEL},
	{MAP_A1_UNDERGROUND_PASSAGE_LEVEL_1, VECTOR_PREV, MAP_A1_STONY_FIELD, TARGET_LEVEL},
	{MAP_A1_UNDERGROUND_PASSAGE_LEVEL_1, VECTOR_QUEST, MAP_A1_UNDERGROUND_PASSAGE_LEVEL_2, TARGET_LEVEL},

	{MAP_A1_DARK_WOOD, VECTOR_NEXT, MAP_A1_BLACK_MARSH, TARGET_LEVEL},
	{MAP_A1_DARK_WOOD, VECTOR_PREV, MAP_A1_UNDERGROUND_PASSAGE_LEVEL_1, TARGET_LEVEL},
	{MAP_A1_DARK_WOOD, VECTOR_QUEST, 30, UNIT_TYPE_OBJECT},

	{MAP_A1_BLACK_MARSH, VECTOR_NEXT, MAP_A1_TAMOE_HIGHLAND, TARGET_LEVEL},
	{MAP_A1_BLACK_MARSH, VECTOR_PREV, MAP_A1_DARK_WOOD, TARGET_LEVEL},
	{MAP_A1_BLACK_MARSH, VECTOR_QUEST, MAP_A1_FORGOTTEN_TOWER, TARGET_LEVEL},

	{MAP_A1_FORGOTTEN_TOWER, VECTOR_QUEST, MAP_A1_TOWER_CELLAR_LEVEL_1, TARGET_LEVEL},
	{MAP_A1_FORGOTTEN_TOWER, VECTOR_PREV, MAP_A1_BLACK_MARSH, TARGET_LEVEL},

	{MAP_A1_TOWER_CELLAR_LEVEL_1, VECTOR_QUEST, MAP_A1_TOWER_CELLAR_LEVEL_2, TARGET_LEVEL},
	{MAP_A1_TOWER_CELLAR_LEVEL_1, VECTOR_PREV, MAP_A1_FORGOTTEN_TOWER, TARGET_LEVEL},

	{MAP_A1_TOWER_CELLAR_LEVEL_2, VECTOR_QUEST, MAP_A1_TOWER_CELLAR_LEVEL_3, TARGET_LEVEL},
	{MAP_A1_TOWER_CELLAR_LEVEL_2, VECTOR_PREV, MAP_A1_TOWER_CELLAR_LEVEL_1, TARGET_LEVEL},

	{MAP_A1_TOWER_CELLAR_LEVEL_3, VECTOR_QUEST, MAP_A1_TOWER_CELLAR_LEVEL_4, TARGET_LEVEL},
	{MAP_A1_TOWER_CELLAR_LEVEL_3, VECTOR_PREV, MAP_A1_TOWER_CELLAR_LEVEL_2, TARGET_LEVEL},

	{MAP_A1_TOWER_CELLAR_LEVEL_4, VECTOR_QUEST, MAP_A1_TOWER_CELLAR_LEVEL_5, TARGET_LEVEL},
	{MAP_A1_TOWER_CELLAR_LEVEL_4, VECTOR_PREV, MAP_A1_TOWER_CELLAR_LEVEL_3, TARGET_LEVEL},

	{MAP_A1_TOWER_CELLAR_LEVEL_5, VECTOR_QUEST, 580, UNIT_TYPE_OBJECT},
	{MAP_A1_TOWER_CELLAR_LEVEL_5, VECTOR_PREV, MAP_A1_TOWER_CELLAR_LEVEL_4, TARGET_LEVEL},

	{MAP_A1_TAMOE_HIGHLAND, VECTOR_NEXT, MAP_A1_MONASTERY_GATE, TARGET_LEVEL},
	{MAP_A1_TAMOE_HIGHLAND, VECTOR_PREV, MAP_A1_BLACK_MARSH, TARGET_LEVEL},
	{MAP_A1_TAMOE_HIGHLAND, VECTOR_QUEST, MAP_A1_PIT_LEVEL_1, TARGET_LEVEL},

	{MAP_A1_PIT_LEVEL_1, VECTOR_QUEST, MAP_A1_PIT_LEVEL_2, TARGET_LEVEL},
	{MAP_A1_PIT_LEVEL_1, VECTOR_PREV, MAP_A1_TAMOE_HIGHLAND, TARGET_LEVEL},

	{MAP_A1_PIT_LEVEL_2, VECTOR_QUEST, 397, UNIT_TYPE_OBJECT},
	{MAP_A1_PIT_LEVEL_2, VECTOR_PREV, MAP_A1_PIT_LEVEL_1, TARGET_LEVEL},

	{MAP_A1_MONASTERY_GATE, VECTOR_NEXT, MAP_A1_OUTER_CLOISTER, TARGET_LEVEL},
	{MAP_A1_MONASTERY_GATE, VECTOR_PREV, MAP_A1_TAMOE_HIGHLAND, TARGET_LEVEL},

	{MAP_A1_OUTER_CLOISTER, VECTOR_NEXT, MAP_A1_BARRACKS, TARGET_LEVEL},
	{MAP_A1_OUTER_CLOISTER, VECTOR_PREV, MAP_A1_MONASTERY_GATE, TARGET_LEVEL},

	{MAP_A1_BARRACKS, VECTOR_NEXT, MAP_A1_JAIL_LEVEL_1, TARGET_LEVEL},
	{MAP_A1_BARRACKS, VECTOR_PREV, MAP_A1_OUTER_CLOISTER, TARGET_LEVEL},
	{MAP_A1_BARRACKS, VECTOR_QUEST, 108, UNIT_TYPE_OBJECT},

	{MAP_A1_JAIL_LEVEL_1, VECTOR_NEXT, MAP_A1_JAIL_LEVEL_2, TARGET_LEVEL},
	{MAP_A1_JAIL_LEVEL_1, VECTOR_PREV, MAP_A1_BARRACKS, TARGET_LEVEL},

	{MAP_A1_JAIL_LEVEL_2, VECTOR_NEXT, MAP_A1_JAIL_LEVEL_3, TARGET_LEVEL},
	{MAP_A1_JAIL_LEVEL_2, VECTOR_PREV, MAP_A1_JAIL_LEVEL_1, TARGET_LEVEL},

	{MAP_A1_JAIL_LEVEL_3, VECTOR_NEXT, MAP_A1_INNER_CLOISTER, TARGET_LEVEL},
	{MAP_A1_JAIL_LEVEL_3, VECTOR_PREV, MAP_A1_JAIL_LEVEL_2, TARGET_LEVEL},

	{MAP_A1_INNER_CLOISTER, VECTOR_NEXT, 25, UNIT_TYPE_OBJECT},
	{MAP_A1_INNER_CLOISTER, VECTOR_PREV, MAP_A1_JAIL_LEVEL_3, TARGET_LEVEL},

	{MAP_A1_INNER_CLOISTER_2, VECTOR_NEXT, MAP_A1_CATACOMBS_LEVEL_1, TARGET_LEVEL},
	{MAP_A1_INNER_CLOISTER_2, VECTOR_PREV, MAP_A1_INNER_CLOISTER, TARGET_LEVEL},
	{MAP_A1_INNER_CLOISTER_2, VECTOR_QUEST, 743, UNIT_TYPE_NPC},

	{MAP_A1_CATACOMBS_LEVEL_1, VECTOR_PREV, MAP_A1_INNER_CLOISTER_2, TARGET_LEVEL},
	{MAP_A1_CATACOMBS_LEVEL_1, VECTOR_NEXT, MAP_A1_CATACOMBS_LEVEL_2, TARGET_LEVEL},

	{MAP_A1_CATACOMBS_LEVEL_2, VECTOR_PREV, MAP_A1_CATACOMBS_LEVEL_1, TARGET_LEVEL},
	{MAP_A1_CATACOMBS_LEVEL_2, VECTOR_NEXT, MAP_A1_CATACOMBS_LEVEL_3, TARGET_LEVEL},

	{MAP_A1_CATACOMBS_LEVEL_3, VECTOR_PREV, MAP_A1_CATACOMBS_LEVEL_2, TARGET_LEVEL},
	{MAP_A1_CATACOMBS_LEVEL_3, VECTOR_NEXT, MAP_A1_CATACOMBS_LEVEL_4, TARGET_LEVEL},

	{MAP_A1_CATACOMBS_LEVEL_4, VECTOR_PREV, 17, UNIT_TYPE_TILE},
	{MAP_A1_CATACOMBS_LEVEL_4, VECTOR_NEXT, 156, UNIT_TYPE_NPC},

				/////////////////////////////////////////////
				/////////////////   Act II  /////////////////
				/////////////////////////////////////////////

	{MAP_A2_ROCKY_WASTE, VECTOR_NEXT, MAP_A2_DRY_HILLS, TARGET_LEVEL},
	{MAP_A2_ROCKY_WASTE, VECTOR_PREV, MAP_A2_LUT_GHOLEIN, TARGET_LEVEL},
	{MAP_A2_ROCKY_WASTE, VECTOR_QUEST, MAP_A2_STONY_TOMB_LEVEL_1, TARGET_LEVEL},

	{MAP_A2_DRY_HILLS, VECTOR_NEXT, MAP_A2_FAR_OASIS, TARGET_LEVEL},
	{MAP_A2_DRY_HILLS, VECTOR_PREV, MAP_A2_ROCKY_WASTE, TARGET_LEVEL},
	{MAP_A2_DRY_HILLS, VECTOR_QUEST, MAP_A2_HALLS_OF_THE_DEAD_LEVEL_1, TARGET_LEVEL},

	{MAP_A2_FAR_OASIS, VECTOR_NEXT, MAP_A2_LOST_CITY, TARGET_LEVEL},
	{MAP_A2_FAR_OASIS, VECTOR_PREV, MAP_A2_DRY_HILLS, TARGET_LEVEL},
	{MAP_A2_FAR_OASIS, VECTOR_QUEST, MAP_A2_MAGGOT_LAIR_LEVEL_1, TARGET_LEVEL},

	{MAP_A2_LOST_CITY, VECTOR_NEXT, MAP_A2_VALLEY_OF_SNAKES, TARGET_LEVEL},
	{MAP_A2_LOST_CITY, VECTOR_PREV, MAP_A2_FAR_OASIS, TARGET_LEVEL},
	{MAP_A2_LOST_CITY, VECTOR_QUEST, MAP_A2_ANCIENT_TUNNELS, TARGET_LEVEL},

	{MAP_A2_ANCIENT_TUNNELS, VECTOR_QUEST, 397, UNIT_TYPE_OBJECT},
	{MAP_A2_ANCIENT_TUNNELS, VECTOR_PREV, MAP_A2_LOST_CITY, TARGET_LEVEL},

	{MAP_A2_VALLEY_OF_SNAKES, VECTOR_NEXT, MAP_A2_CLAW_VIPER_TEMPLE_LEVEL_1, TARGET_LEVEL},
	{MAP_A2_VALLEY_OF_SNAKES, VECTOR_PREV, MAP_A2_LOST_CITY, TARGET_LEVEL},

	{MAP_A2_CLAW_VIPER_TEMPLE_LEVEL_1, VECTOR_NEXT, MAP_A2_CLAW_VIPER_TEMPLE_LEVEL_2, TARGET_LEVEL},
	{MAP_A2_CLAW_VIPER_TEMPLE_LEVEL_1, VECTOR_PREV, MAP_A2_VALLEY_OF_SNAKES, TARGET_LEVEL},

	{MAP_A2_CLAW_VIPER_TEMPLE_LEVEL_2, VECTOR_NEXT, 149, UNIT_TYPE_OBJECT},
	{MAP_A2_CLAW_VIPER_TEMPLE_LEVEL_2, VECTOR_PREV, MAP_A2_CLAW_VIPER_TEMPLE_LEVEL_1, TARGET_LEVEL},

	{MAP_A2_HAREM_LEVEL_1, VECTOR_NEXT, 29, UNIT_TYPE_TILE},
	{MAP_A2_HAREM_LEVEL_1, VECTOR_PREV, MAP_A2_LUT_GHOLEIN, TARGET_LEVEL},

	{MAP_A2_HAREM_LEVEL_2, VECTOR_NEXT, MAP_A2_PALACE_CELLAR_LEVEL_1, TARGET_LEVEL},
	{MAP_A2_HAREM_LEVEL_2, VECTOR_PREV, 27, UNIT_TYPE_TILE},

	{MAP_A2_PALACE_CELLAR_LEVEL_1, VECTOR_NEXT, MAP_A2_PALACE_CELLAR_LEVEL_2, TARGET_LEVEL},
	{MAP_A2_PALACE_CELLAR_LEVEL_1, VECTOR_PREV, 27, UNIT_TYPE_TILE},

	{MAP_A2_PALACE_CELLAR_LEVEL_2, VECTOR_NEXT, MAP_A2_PALACE_CELLAR_LEVEL_3, TARGET_LEVEL},
	{MAP_A2_PALACE_CELLAR_LEVEL_2, VECTOR_PREV, 31, UNIT_TYPE_TILE},

	{MAP_A2_PALACE_CELLAR_LEVEL_3, VECTOR_NEXT, 298, UNIT_TYPE_OBJECT},
	{MAP_A2_PALACE_CELLAR_LEVEL_3, VECTOR_PREV, 31, UNIT_TYPE_TILE},

	{MAP_A2_ARCANE_SANCTUARY, VECTOR_NEXT, 357, UNIT_TYPE_OBJECT},
	{MAP_A2_ARCANE_SANCTUARY, VECTOR_PREV, 298, UNIT_TYPE_OBJECT},

	{MAP_A2_SEWERS_LEVEL_1, VECTOR_NEXT, MAP_A2_SEWERS_LEVEL_2, TARGET_LEVEL},
	{MAP_A2_SEWERS_LEVEL_1, VECTOR_PREV, MAP_A2_LUT_GHOLEIN, TARGET_LEVEL},

	{MAP_A2_SEWERS_LEVEL_2, VECTOR_NEXT, MAP_A2_SEWERS_LEVEL_3, TARGET_LEVEL},
	{MAP_A2_SEWERS_LEVEL_2, VECTOR_PREV, MAP_A2_SEWERS_LEVEL_1, TARGET_LEVEL},

	{MAP_A2_SEWERS_LEVEL_3, VECTOR_NEXT, 355, UNIT_TYPE_OBJECT},
	{MAP_A2_SEWERS_LEVEL_3, VECTOR_PREV, MAP_A2_SEWERS_LEVEL_2, TARGET_LEVEL},

	{MAP_A2_HALLS_OF_THE_DEAD_LEVEL_1, VECTOR_QUEST, MAP_A2_HALLS_OF_THE_DEAD_LEVEL_2, TARGET_LEVEL},
	{MAP_A2_HALLS_OF_THE_DEAD_LEVEL_1, VECTOR_PREV, MAP_A2_DRY_HILLS, TARGET_LEVEL},

	{MAP_A2_HALLS_OF_THE_DEAD_LEVEL_2, VECTOR_QUEST, MAP_A2_HALLS_OF_THE_DEAD_LEVEL_3, TARGET_LEVEL},
	{MAP_A2_HALLS_OF_THE_DEAD_LEVEL_2, VECTOR_PREV, MAP_A2_HALLS_OF_THE_DEAD_LEVEL_1, TARGET_LEVEL},

	{MAP_A2_HALLS_OF_THE_DEAD_LEVEL_3, VECTOR_QUEST, 354, UNIT_TYPE_OBJECT},
	{MAP_A2_HALLS_OF_THE_DEAD_LEVEL_3, VECTOR_PREV, MAP_A2_HALLS_OF_THE_DEAD_LEVEL_2, TARGET_LEVEL},

	{MAP_A2_MAGGOT_LAIR_LEVEL_1, VECTOR_QUEST, MAP_A2_MAGGOT_LAIR_LEVEL_2, TARGET_LEVEL},
	{MAP_A2_MAGGOT_LAIR_LEVEL_1, VECTOR_PREV, MAP_A2_FAR_OASIS, TARGET_LEVEL},

	{MAP_A2_MAGGOT_LAIR_LEVEL_2, VECTOR_QUEST, MAP_A2_MAGGOT_LAIR_LEVEL_3, TARGET_LEVEL},
	{MAP_A2_MAGGOT_LAIR_LEVEL_2, VECTOR_PREV, MAP_A2_MAGGOT_LAIR_LEVEL_1, TARGET_LEVEL},

	{MAP_A2_MAGGOT_LAIR_LEVEL_3, VECTOR_QUEST, 356, UNIT_TYPE_OBJECT},
	{MAP_A2_MAGGOT_LAIR_LEVEL_3, VECTOR_PREV, MAP_A2_MAGGOT_LAIR_LEVEL_2, TARGET_LEVEL},

	{MAP_A2_STONY_TOMB_LEVEL_1, VECTOR_QUEST, MAP_A2_STONY_TOMB_LEVEL_2, TARGET_LEVEL},
	{MAP_A2_STONY_TOMB_LEVEL_1, VECTOR_PREV, MAP_A2_ROCKY_WASTE, TARGET_LEVEL},

	{MAP_A2_STONY_TOMB_LEVEL_2, VECTOR_QUEST, 397, UNIT_TYPE_OBJECT},
	{MAP_A2_STONY_TOMB_LEVEL_2, VECTOR_PREV, MAP_A2_STONY_TOMB_LEVEL_1, TARGET_LEVEL},

	{MAP_A2_TAL_RASHAS_TOMB_1, VECTOR_NEXT, 152, UNIT_TYPE_OBJECT},
	{MAP_A2_TAL_RASHAS_TOMB_2, VECTOR_NEXT, 152, UNIT_TYPE_OBJECT},
	{MAP_A2_TAL_RASHAS_TOMB_3, VECTOR_NEXT, 152, UNIT_TYPE_OBJECT},
	{MAP_A2_TAL_RASHAS_TOMB_4, VECTOR_NEXT, 152, UNIT_TYPE_OBJECT},
	{MAP_A2_TAL_RASHAS_TOMB_5, VECTOR_NEXT, 152, UNIT_TYPE_OBJECT},
	{MAP_A2_TAL_RASHAS_TOMB_6, VECTOR_NEXT, 152, UNIT_TYPE_OBJECT},
	{MAP_A2_TAL_RASHAS_TOMB_7, VECTOR_NEXT, 152, UNIT_TYPE_OBJECT},

	{MAP_A2_TAL_RASHAS_TOMB_1, VECTOR_NEXT, 397, UNIT_TYPE_OBJECT},
	{MAP_A2_TAL_RASHAS_TOMB_2, VECTOR_NEXT, 397, UNIT_TYPE_OBJECT},
	{MAP_A2_TAL_RASHAS_TOMB_3, VECTOR_NEXT, 397, UNIT_TYPE_OBJECT},
	{MAP_A2_TAL_RASHAS_TOMB_4, VECTOR_NEXT, 397, UNIT_TYPE_OBJECT},
	{MAP_A2_TAL_RASHAS_TOMB_5, VECTOR_NEXT, 397, UNIT_TYPE_OBJECT},
	{MAP_A2_TAL_RASHAS_TOMB_6, VECTOR_NEXT, 397, UNIT_TYPE_OBJECT},
	{MAP_A2_TAL_RASHAS_TOMB_7, VECTOR_NEXT, 397, UNIT_TYPE_OBJECT},

	{MAP_A2_TAL_RASHAS_TOMB_1, VECTOR_PREV, 45, UNIT_TYPE_TILE},
	{MAP_A2_TAL_RASHAS_TOMB_2, VECTOR_PREV, 45, UNIT_TYPE_TILE},
	{MAP_A2_TAL_RASHAS_TOMB_3, VECTOR_PREV, 45, UNIT_TYPE_TILE},
	{MAP_A2_TAL_RASHAS_TOMB_4, VECTOR_PREV, 45, UNIT_TYPE_TILE},
	{MAP_A2_TAL_RASHAS_TOMB_5, VECTOR_PREV, 45, UNIT_TYPE_TILE},
	{MAP_A2_TAL_RASHAS_TOMB_6, VECTOR_PREV, 45, UNIT_TYPE_TILE},
	{MAP_A2_TAL_RASHAS_TOMB_7, VECTOR_PREV, 45, UNIT_TYPE_TILE},

	{MAP_A2_CANYON_OF_THE_MAGI, VECTOR_NEXT, 38, UNIT_TYPE_TILE},
	{MAP_A2_CANYON_OF_THE_MAGI, VECTOR_NEXT, 39, UNIT_TYPE_TILE},
	{MAP_A2_CANYON_OF_THE_MAGI, VECTOR_NEXT, 40, UNIT_TYPE_TILE},
	{MAP_A2_CANYON_OF_THE_MAGI, VECTOR_NEXT, 41, UNIT_TYPE_TILE},
	{MAP_A2_CANYON_OF_THE_MAGI, VECTOR_NEXT, 42, UNIT_TYPE_TILE},
	{MAP_A2_CANYON_OF_THE_MAGI, VECTOR_NEXT, 43, UNIT_TYPE_TILE},
	{MAP_A2_CANYON_OF_THE_MAGI, VECTOR_NEXT, 44, UNIT_TYPE_TILE},

				/////////////////////////////////////////////
				/////////////////  Act III  /////////////////
				/////////////////////////////////////////////

	{MAP_A3_SPIDER_FOREST, VECTOR_NEXT, MAP_A3_FLAYER_JUNGLE, TARGET_LEVEL},
	{MAP_A3_SPIDER_FOREST, VECTOR_NEXT, MAP_A3_GREAT_MARSH, TARGET_LEVEL},
	{MAP_A3_SPIDER_FOREST, VECTOR_PREV, MAP_A3_KURAST_DOCKS, TARGET_LEVEL},
	{MAP_A3_SPIDER_FOREST, VECTOR_QUEST, MAP_A3_SPIDER_CAVERN, TARGET_LEVEL},

	{MAP_A3_SPIDER_CAVERN, VECTOR_QUEST, 407, UNIT_TYPE_OBJECT},
	{MAP_A3_SPIDER_CAVERN, VECTOR_PREV, MAP_A3_SPIDER_FOREST, TARGET_LEVEL},

	{MAP_A3_ARCHNID_LAIR, VECTOR_NEXT, 397, UNIT_TYPE_OBJECT},
	{MAP_A3_ARCHNID_LAIR, VECTOR_PREV, MAP_A3_SPIDER_FOREST, TARGET_LEVEL},

	{MAP_A3_GREAT_MARSH, VECTOR_NEXT, MAP_A3_FLAYER_JUNGLE, TARGET_LEVEL},
	{MAP_A3_GREAT_MARSH, VECTOR_PREV, MAP_A3_SPIDER_FOREST, TARGET_LEVEL},

	{MAP_A3_FLAYER_JUNGLE, VECTOR_NEXT, MAP_A3_LOWER_KURAST, TARGET_LEVEL},
	{MAP_A3_FLAYER_JUNGLE, VECTOR_PREV, MAP_A3_SPIDER_FOREST, TARGET_LEVEL},
	{MAP_A3_FLAYER_JUNGLE, VECTOR_PREV, MAP_A3_GREAT_MARSH, TARGET_LEVEL},
	{MAP_A3_FLAYER_JUNGLE, VECTOR_QUEST, 54, UNIT_TYPE_TILE},

	{MAP_A3_LOWER_KURAST, VECTOR_NEXT, MAP_A3_KURAST_BAZAAR, TARGET_LEVEL},
	{MAP_A3_LOWER_KURAST, VECTOR_PREV, MAP_A3_FLAYER_JUNGLE, TARGET_LEVEL},

	{MAP_A3_KURAST_BAZAAR, VECTOR_NEXT, MAP_A3_UPPER_KURAST, TARGET_LEVEL},
	{MAP_A3_KURAST_BAZAAR, VECTOR_PREV, MAP_A3_LOWER_KURAST, TARGET_LEVEL},
	{MAP_A3_KURAST_BAZAAR, VECTOR_QUEST, 195, UNIT_TYPE_OBJECT},

	{MAP_A3_UPPER_KURAST, VECTOR_NEXT, MAP_A3_KURAST_CAUSEWAY, TARGET_LEVEL},
	{MAP_A3_UPPER_KURAST, VECTOR_PREV, MAP_A3_KURAST_BAZAAR, TARGET_LEVEL},
	{MAP_A3_UPPER_KURAST, VECTOR_QUEST, MAP_A3_SEWERS_LEVEL_1, TARGET_LEVEL},

	{MAP_A3_SEWERS_LEVEL_1, VECTOR_QUEST, MAP_A3_SEWERS_LEVEL_2, TARGET_LEVEL},
	{MAP_A3_SEWERS_LEVEL_1, VECTOR_PREV, MAP_A3_UPPER_KURAST, TARGET_LEVEL},

	{MAP_A3_SEWERS_LEVEL_2, VECTOR_QUEST, 405, UNIT_TYPE_OBJECT},
	{MAP_A3_SEWERS_LEVEL_2, VECTOR_PREV, MAP_A3_SEWERS_LEVEL_1, TARGET_LEVEL},

	{MAP_A3_KURAST_CAUSEWAY, VECTOR_NEXT, MAP_A3_TRAVINCAL, TARGET_LEVEL},
	{MAP_A3_KURAST_CAUSEWAY, VECTOR_PREV, MAP_A3_UPPER_KURAST, TARGET_LEVEL},

	{MAP_A3_TRAVINCAL, VECTOR_NEXT, 386, UNIT_TYPE_OBJECT},
	{MAP_A3_TRAVINCAL, VECTOR_PREV, MAP_A3_KURAST_CAUSEWAY, TARGET_LEVEL},

	{MAP_A3_DURANCE_OF_HATE_LEVEL_1, VECTOR_NEXT, MAP_A3_DURANCE_OF_HATE_LEVEL_2, TARGET_LEVEL},
	{MAP_A3_DURANCE_OF_HATE_LEVEL_1, VECTOR_PREV, MAP_A3_TRAVINCAL, TARGET_LEVEL},

	{MAP_A3_DURANCE_OF_HATE_LEVEL_2, VECTOR_NEXT, MAP_A3_DURANCE_OF_HATE_LEVEL_3, TARGET_LEVEL},
	{MAP_A3_DURANCE_OF_HATE_LEVEL_2, VECTOR_PREV, MAP_A3_DURANCE_OF_HATE_LEVEL_1, TARGET_LEVEL},

	{MAP_A3_DURANCE_OF_HATE_LEVEL_3, VECTOR_NEXT, 242, UNIT_TYPE_NPC},
	{MAP_A3_DURANCE_OF_HATE_LEVEL_3, VECTOR_PREV, MAP_A3_DURANCE_OF_HATE_LEVEL_2, TARGET_LEVEL},

	{MAP_A3_SWAMPY_PIT_LEVEL_1, VECTOR_NEXT, MAP_A3_SWAMPY_PIT_LEVEL_2, TARGET_LEVEL},
	{MAP_A3_SWAMPY_PIT_LEVEL_1, VECTOR_PREV, MAP_A3_FLAYER_JUNGLE, TARGET_LEVEL},

	{MAP_A3_SWAMPY_PIT_LEVEL_2, VECTOR_NEXT, MAP_A3_SWAMPY_PIT_LEVEL_3, TARGET_LEVEL},
	{MAP_A3_SWAMPY_PIT_LEVEL_2, VECTOR_PREV, MAP_A3_SWAMPY_PIT_LEVEL_1, TARGET_LEVEL},

	{MAP_A3_SWAMPY_PIT_LEVEL_3, VECTOR_NEXT, 397, UNIT_TYPE_OBJECT},
	{MAP_A3_SWAMPY_PIT_LEVEL_3, VECTOR_PREV, MAP_A3_SWAMPY_PIT_LEVEL_2, TARGET_LEVEL},

	{MAP_A3_FLAYER_DUNGEON_LEVEL_1, VECTOR_QUEST, MAP_A3_FLAYER_DUNGEON_LEVEL_2, TARGET_LEVEL},
	{MAP_A3_FLAYER_DUNGEON_LEVEL_1, VECTOR_PREV, MAP_A3_FLAYER_JUNGLE, TARGET_LEVEL},

	{MAP_A3_FLAYER_DUNGEON_LEVEL_2, VECTOR_QUEST, MAP_A3_FLAYER_DUNGEON_LEVEL_3, TARGET_LEVEL},
	{MAP_A3_FLAYER_DUNGEON_LEVEL_2, VECTOR_PREV, MAP_A3_FLAYER_DUNGEON_LEVEL_1, TARGET_LEVEL},

	{MAP_A3_FLAYER_DUNGEON_LEVEL_3, VECTOR_QUEST, 406, UNIT_TYPE_OBJECT},
	{MAP_A3_FLAYER_DUNGEON_LEVEL_3, VECTOR_PREV, MAP_A3_FLAYER_DUNGEON_LEVEL_2, TARGET_LEVEL},

	{MAP_A3_RUINED_TEMPLE, VECTOR_QUEST, 193, UNIT_TYPE_OBJECT},
	{MAP_A3_RUINED_TEMPLE, VECTOR_PREV, MAP_A3_KURAST_BAZAAR, TARGET_LEVEL},
	{MAP_A3_DISUSED_FANE, VECTOR_PREV, MAP_A3_KURAST_BAZAAR, TARGET_LEVEL},
	{MAP_A3_FORGOTTEN_TEMPLE, VECTOR_PREV, MAP_A3_UPPER_KURAST, TARGET_LEVEL},
	{MAP_A3_FORGOTTEN_RELIQUARY, VECTOR_PREV, MAP_A3_UPPER_KURAST, TARGET_LEVEL},
	{MAP_A3_RUINED_FANE, VECTOR_PREV, MAP_A3_KURAST_CAUSEWAY, TARGET_LEVEL},
	{MAP_A3_DISUSED_RELIQUARY, VECTOR_PREV, MAP_A3_KURAST_CAUSEWAY, TARGET_LEVEL},

				/////////////////////////////////////////////
				/////////////////   Act IV  /////////////////
				/////////////////////////////////////////////

	{MAP_A4_OUTER_STEPPES, VECTOR_NEXT, MAP_A4_PLAINS_OF_DESPAIR, TARGET_LEVEL},
	{MAP_A4_OUTER_STEPPES, VECTOR_PREV, MAP_A4_THE_PANDEMONIUM_FORTRESS, TARGET_LEVEL},

	{MAP_A4_PLAINS_OF_DESPAIR, VECTOR_NEXT, MAP_A4_CITY_OF_THE_DAMNED, TARGET_LEVEL},
	{MAP_A4_PLAINS_OF_DESPAIR, VECTOR_PREV, MAP_A4_OUTER_STEPPES, TARGET_LEVEL},
	{MAP_A4_PLAINS_OF_DESPAIR, VECTOR_QUEST, 256, UNIT_TYPE_NPC},

	{MAP_A4_CITY_OF_THE_DAMNED, VECTOR_NEXT, MAP_A4_RIVER_OF_FLAME, TARGET_LEVEL},
	{MAP_A4_CITY_OF_THE_DAMNED, VECTOR_PREV, MAP_A4_PLAINS_OF_DESPAIR, TARGET_LEVEL},

	{MAP_A4_RIVER_OF_FLAME, VECTOR_NEXT, MAP_A4_THE_CHAOS_SANCTUARY, TARGET_LEVEL},
	{MAP_A4_RIVER_OF_FLAME, VECTOR_PREV, MAP_A4_CITY_OF_THE_DAMNED, TARGET_LEVEL},
	{MAP_A4_RIVER_OF_FLAME, VECTOR_QUEST, 775, UNIT_TYPE_NPC},

	{MAP_A4_THE_CHAOS_SANCTUARY, VECTOR_NEXT, 255, UNIT_TYPE_OBJECT},
	{MAP_A4_THE_CHAOS_SANCTUARY, VECTOR_PREV, MAP_A4_RIVER_OF_FLAME, TARGET_LEVEL},

				/////////////////////////////////////////////
				/////////////////   Act V   /////////////////
				/////////////////////////////////////////////

	{MAP_A5_THE_BLOODY_FOOTHILLS, VECTOR_NEXT, MAP_A5_FRIGID_HIGHLANDS, TARGET_LEVEL},
	{MAP_A5_THE_BLOODY_FOOTHILLS, VECTOR_PREV, MAP_A5_HARROGATH, TARGET_LEVEL},
	{MAP_A5_THE_BLOODY_FOOTHILLS, VECTOR_QUEST, 776, UNIT_TYPE_NPC},

	{MAP_A5_FRIGID_HIGHLANDS, VECTOR_NEXT, MAP_A5_ARREAT_PLATEAU, TARGET_LEVEL},
	{MAP_A5_FRIGID_HIGHLANDS, VECTOR_PREV, MAP_A5_THE_BLOODY_FOOTHILLS, TARGET_LEVEL},

	{MAP_A5_FRIGID_HIGHLANDS, VECTOR_QUEST, 60, UNIT_TYPE_OBJECT},
	{MAP_A5_ARREAT_PLATEAU, VECTOR_QUEST, 60, UNIT_TYPE_OBJECT},
	{MAP_A5_FROZEN_TUNDRA, VECTOR_QUEST, 60, UNIT_TYPE_OBJECT},

	{MAP_A5_ABADDON, VECTOR_QUEST, 397, UNIT_TYPE_OBJECT},
	{MAP_A5_ABADDON, VECTOR_PREV, 60, UNIT_TYPE_OBJECT},
	{MAP_A5_PIT_OF_ACHERON, VECTOR_QUEST, 397, UNIT_TYPE_OBJECT},
	{MAP_A5_PIT_OF_ACHERON, VECTOR_PREV, 60, UNIT_TYPE_OBJECT},
	{MAP_A5_INFERNAL_PIT, VECTOR_QUEST, 397, UNIT_TYPE_OBJECT},
	{MAP_A5_INFERNAL_PIT, VECTOR_PREV, 60, UNIT_TYPE_OBJECT},

	{MAP_A5_ARREAT_PLATEAU, VECTOR_NEXT, MAP_A5_CRYSTALLINE_PASSAGE, TARGET_LEVEL},
	{MAP_A5_ARREAT_PLATEAU, VECTOR_PREV, MAP_A5_FRIGID_HIGHLANDS, TARGET_LEVEL},

	{MAP_A5_CRYSTALLINE_PASSAGE, VECTOR_NEXT, MAP_A5_GLACIAL_TRAIL, TARGET_LEVEL},
	{MAP_A5_CRYSTALLINE_PASSAGE, VECTOR_PREV, MAP_A5_ARREAT_PLATEAU, TARGET_LEVEL},
	{MAP_A5_CRYSTALLINE_PASSAGE, VECTOR_QUEST, MAP_A5_FROZEN_RIVER, TARGET_LEVEL},

	{MAP_A5_FROZEN_RIVER, VECTOR_QUEST, 793, UNIT_TYPE_NPC},
	{MAP_A5_FROZEN_RIVER, VECTOR_PREV, MAP_A5_CRYSTALLINE_PASSAGE, TARGET_LEVEL},

	{MAP_A5_GLACIAL_TRAIL, VECTOR_NEXT, MAP_A5_FROZEN_TUNDRA, TARGET_LEVEL},
	{MAP_A5_GLACIAL_TRAIL, VECTOR_PREV, MAP_A5_CRYSTALLINE_PASSAGE, TARGET_LEVEL},
	{MAP_A5_GLACIAL_TRAIL, VECTOR_QUEST, MAP_A5_DRIFTER_CAVERN, TARGET_LEVEL},
	
	{MAP_A5_DRIFTER_CAVERN, VECTOR_QUEST, 397, UNIT_TYPE_OBJECT},
	{MAP_A5_DRIFTER_CAVERN, VECTOR_PREV, MAP_A5_GLACIAL_TRAIL, TARGET_LEVEL},

	{MAP_A5_FROZEN_TUNDRA, VECTOR_NEXT, MAP_A5_THE_ANCIENTS_WAY, TARGET_LEVEL},
	{MAP_A5_FROZEN_TUNDRA, VECTOR_PREV, MAP_A5_GLACIAL_TRAIL, TARGET_LEVEL},

	{MAP_A5_THE_ANCIENTS_WAY, VECTOR_NEXT, MAP_A5_ARREAT_SUMMIT, TARGET_LEVEL},
	{MAP_A5_THE_ANCIENTS_WAY, VECTOR_PREV, MAP_A5_FROZEN_TUNDRA, TARGET_LEVEL},
	{MAP_A5_THE_ANCIENTS_WAY, VECTOR_QUEST, MAP_A5_ICY_CELLAR, TARGET_LEVEL},
	
	{MAP_A5_ICY_CELLAR, VECTOR_QUEST, 397, UNIT_TYPE_OBJECT},
	{MAP_A5_ICY_CELLAR, VECTOR_PREV, MAP_A5_THE_ANCIENTS_WAY, TARGET_LEVEL},

	{MAP_A5_ARREAT_SUMMIT, VECTOR_NEXT, MAP_A5_WORLDSTONE_KEEP_LEVEL_1, TARGET_LEVEL},
	{MAP_A5_ARREAT_SUMMIT, VECTOR_PREV, MAP_A5_THE_ANCIENTS_WAY, TARGET_LEVEL},
	{MAP_A5_ARREAT_SUMMIT, VECTOR_QUEST, 546, UNIT_TYPE_OBJECT},

	{MAP_A5_WORLDSTONE_KEEP_LEVEL_1, VECTOR_NEXT, MAP_A5_WORLDSTONE_KEEP_LEVEL_2, TARGET_LEVEL},
	{MAP_A5_WORLDSTONE_KEEP_LEVEL_1, VECTOR_PREV, MAP_A5_ARREAT_SUMMIT, TARGET_LEVEL},

	{MAP_A5_WORLDSTONE_KEEP_LEVEL_2, VECTOR_NEXT, MAP_A5_WORLDSTONE_KEEP_LEVEL_3, TARGET_LEVEL},
	{MAP_A5_WORLDSTONE_KEEP_LEVEL_2, VECTOR_PREV, MAP_A5_WORLDSTONE_KEEP_LEVEL_1, TARGET_LEVEL},

	{MAP_A5_WORLDSTONE_KEEP_LEVEL_3, VECTOR_NEXT, MAP_A5_THRONE_OF_DESTRUCTION, TARGET_LEVEL},
	{MAP_A5_WORLDSTONE_KEEP_LEVEL_3, VECTOR_PREV, MAP_A5_WORLDSTONE_KEEP_LEVEL_2, TARGET_LEVEL},

	{MAP_A5_THRONE_OF_DESTRUCTION, VECTOR_NEXT, 563, UNIT_TYPE_OBJECT},
	{MAP_A5_THRONE_OF_DESTRUCTION, VECTOR_PREV, MAP_A5_WORLDSTONE_KEEP_LEVEL_3, TARGET_LEVEL},
	
	{MAP_A5_WORLDSTONE_KEEP, VECTOR_NEXT, 544, UNIT_TYPE_NPC},

	{MAP_A5_NIHLATHAKS_TEMPLE, VECTOR_NEXT, MAP_A5_HALLS_OF_ANGUISH, TARGET_LEVEL},

	{MAP_A5_HALLS_OF_ANGUISH, VECTOR_NEXT, MAP_A5_HALLS_OF_PAIN, TARGET_LEVEL},
	{MAP_A5_HALLS_OF_ANGUISH, VECTOR_PREV, MAP_A5_NIHLATHAKS_TEMPLE, TARGET_LEVEL},

	{MAP_A5_HALLS_OF_PAIN, VECTOR_NEXT, MAP_A5_HALLS_OF_VAUGHT, TARGET_LEVEL},
	{MAP_A5_HALLS_OF_PAIN, VECTOR_PREV, MAP_A5_HALLS_OF_ANGUISH, TARGET_LEVEL},

	{MAP_A5_HALLS_OF_VAUGHT, VECTOR_QUEST, 462, UNIT_TYPE_OBJECT},
	{MAP_A5_HALLS_OF_VAUGHT, VECTOR_PREV, MAP_A5_HALLS_OF_PAIN, TARGET_LEVEL},
};