typedef BOOL (_stdcall *fp)(UnitAny* pUnit);

VOID MyMultiByteToWideChar(UINT CodePage, DWORD dwFlags, LPCSTR lpMultiByteStr, INT cbMultiByte, LPWSTR lpWideCharStr, INT cchWideChar);
VOID FlashPlayer(DWORD ID);
VOID SQ(DWORD ID);
VOID SendBNMessage(PCHAR lpMsg);
VOID WinampHook(INT xPos, INT yPos, DWORD dwColor, INT dwFont, INT dwCenter, LPSTR Text,...);
VOID ToggleInventory(BOOL on);
VOID DrawRectangle(INT x, INT y, INT x2, INT y2, DWORD dwColor, DWORD dwTrans);
VOID ResetValues();
VOID Tele(WORD x,WORD y);
VOID Update(DWORD ID);
VOID DrawBlob(INT xpos, INT ypos,INT col);
VOID Hostile(DWORD ID);
VOID HostileAll();
VOID PrintMessage(PCHAR Message, CHAR Color);
VOID PrintMessageBottomLeft(PCHAR Message, CHAR Color);
VOID DrawTextToScreen(PCHAR szwText, INT x, INT y, INT color, INT font);
VOID DrawTextToScreenRight(PCHAR szwText, INT x, INT y, INT color, INT font);
VOID DrawTextToScreenCenter(PCHAR szwText, INT x, INT y, INT color, INT font);
VOID PrintString(LPSTR lpFormat, ...);
VOID PrintFormatString(LPSTR lpFormat, ...);
VOID PrintStringOverhead(LPSTR lpFormat, ...);
VOID OverheadMessage(char *Message);
VOID GetD2MousePos(POINT &Pointer);
VOID HoldRightUp(long X, long Y);
VOID D2DrawRectFrame(INT x,INT y,INT x2,INT y2);
VOID MapToScreenCoords(POINT& rMapPosition);
VOID fpEnumUnits(fp EnumFunction,DWORD Type);
VOID AbsToScreenCoords(POINT& rMapPosition);
VOID ScreenToAutomapRelative(POINT* pos, INT x, INT y);
VOID NewEnum();
VOID MiniMapCell(INT xpos, INT ypos, INT actnum,INT lvlnum, INT fileno, long rx, long ry,DWORD ObjID);
VOID DrawPlayerBlob(INT xpos, INT ypos,INT col);
VOID D2DrawLine(INT x,INT y,INT x2, INT y2, DWORD color);
BOOL SetSkill(WORD wSkillId, BOOL bLeft);
BOOL Speak(LPSTR lpMessage, ...);
BOOL SendWhisper(LPSTR lpMessage, ...);
BOOL IsInventoryOpen();
BOOL D2GetMapName(BYTE iMapID, LPSTR lpszBuffer, DWORD dwMaxChars);
BOOL CheckParty(INT Status);
BOOL ChickenHostile(INT nValue, DWORD PlayerID);
BOOL ChickenAim(INT nValue, DWORD ID, DWORD AimID);
BOOL Spoof();
BOOL MakeTP();
BOOL UseItem(UnitAny* Unit);
BOOL GetItemCode(UnitAny* pItem, LPSTR szBuffer, DWORD dwMax);
BOOL IsTownLevel(INT nLevel);
PCHAR ReplaceString(PCHAR source, PCHAR old, PCHAR newtext);
PCHAR CheckQuest(INT nQuest);
PCHAR GetNameByID(DWORD PID);
PCHAR GetD2ClassName(DWORD ClassID);
PCHAR GetD2ClassName2(DWORD ClassID);
PCHAR GetD2LevelName(DWORD LevelID);
PCHAR mitoa(INT integer);
INT GetPlayerClassName(INT nClass, LPSTR szBuffer, DWORD dwMaxLen);
INT MakeParameter(PCHAR szInput, PCHAR* argv, CHAR splitchar, BOOL bSkipQuote);
INT RandomNumber(INT high, INT low);
INT	GetSkill(WORD wSkillId);
INT GetPercent(DWORD Current,DWORD Max);
INT GetLevelByN(PCHAR Name);
INT GetItemLocation(UnitAny* pItem);
INT GetTPs();
INT D2GetScreenSizeX();
INT D2GetScreenSizeY();
POINT GetPosition();
DWORD GetExpLeft();
DWORD IsExpansion();
DWORD GetTileLevelNo(Room2* lpRoom2, DWORD dwTileNo);
DWORD GetDistance(DWORD x1, DWORD y1, DWORD x2, DWORD y2);
DWORD GetDistanceSquared(DWORD x1, DWORD y1, DWORD x2, DWORD y2);
DWORD CheckSkill(DWORD Skill);
DWORD GetPlayerArea(VOID);
DWORD GetUnitIDByXY(LONG Wx,LONG Wy, Room2* pRoom2);
WORD GetCurrentSkillLeft();
WORD GetCurrentSkillRight();
GameStructInfo* GetGameInfo();
Level* GetLevel(DWORD dwLevelNo);
RosterUnit* FindPartyByName(LPSTR szName);
UnitAny* FindItem(LPCSTR szCode, INT nLoc);
Level* GetUnitLevel(UnitAny* pUnit);
Level* GetLevelPointerD(ActMisc *pActMisc, INT nLevel);
PresetUnit* FindPresetUnit(DWORD dwTxtFileNo, DWORD dwType, Room2* *pRoom);